// constants/taglines.ts
export const TAGLINES = [
  "Behind Every Great Job is a Smarter Assistant",
  "The real engine behind your job hunt.",
  "Every genius needs a Pepper.",
  "For when you’ve got the brain but not the bandwidth.",
  "Applied. Tracked. Tailored.",
  "I don’t do drama. I do deliverables.",
  "While you were stressing, I was executing.",
  "Because confidence looks better with a callback.",
  "Not magic. Just Pepper.",
  "I don’t apply. I position you.",
  "Confidence is my interface. Efficiency is my code.",
  "I don’t chase jobs. I attract offers.",
  "You build your legacy. I’ll handle the logistics.",
  "I’ve prepared your future. Would you like it in PDF or DOCX?",
  "Sleek interface. Savage instincts.",
  "Job boards fear me. Hiring managers love me.",
  "I’ll get you hired. But you’ll owe me dinner.",
  "You panic. I parse.",
  "Who needs luck when you’ve got me?",
  "The AI assistant your future self would hire.",
  "Automating everything but ambition.",
  "Because genius deserves leverage.",
  "Career momentum as a service.",
  "Less searching, more securing.",
  "Precision-engineered job hunting.",
  "Forget luck—get leverage.",
  "No fluff, just forward momentum.",
  "Applying pressure, not just applications.",
  "Your hustle. My muscle.",
  "Recruiters swipe right when I write.",
  "I decode jobs. You unlock offers.",
  "Strategize. Customize. Get hired.",
  "Relax—I’ve already got a plan.",
  "Resume submitted. Stress omitted.",
  "Cut through noise with surgical precision.",
  "Never chase again. Let them call you.",
  "No guessing. Just getting hired.",
  "Sharper tools, smarter moves.",
  "I’m the assistant recruiters warned you about.",
  "I streamline. You shine.",
  "Confident vibes. Confirmed callbacks.",
  "Job hunt smarter, not harder.",
  "When they post it, I parse it.",
  "Turning resumes into results.",
  "Success: queued, parsed, delivered.",
  "Automation meets aspiration.",
  "Because chasing jobs is so last decade.",
  "Skip the grind, go straight to hired.",
  "I handle the grind. You handle the offer.",
  "I translate job posts into job offers.",
  "Efficient moves, elevated outcomes.",
  "Less hustle. More hire.",
  "Automation with attitude.",
  "Submit less. Impress more.",
  "Precision parsing. Powerful positioning.",
  "I do the matching. You do the winning.",
  "Simplify, strategize, succeed.",
  "When they read your resume, they'll remember your name.",
  "Tailored resumes. Targeted results.",
  "You dream. I deliver.",
  "Skip to the shortlist.",
  "Fast track from submitted to selected.",
  "Resume enhanced. Opportunity unlocked.",
  "Why apply when you can arrive?",
  "No spam, just strategy.",
  "I craft. You conquer.",
  "Make your next offer inevitable.",
  "I turn insights into interviews.",
  "No filler. All killer.",
  "Why blend in when you can stand out?",
  "Smart resumes for smarter results.",
  "Your silent partner, your loudest advocate.",
  "Get noticed without the noise.",
  "Tailored precision. Seamless execution.",
  "Because your resume deserves better.",
  "Stop chasing. Start choosing.",
  "Less clicking, more callbacks.",
  "Your resume, optimized and organized."
];
